spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true # ?? ????? logger ??? ??? ?
        format_sql: true
logging:
  level:
    org.hibernate:
      SQL: debug
      orm.jdbc.bind: trace #??? ?? 3.x, hibernate6
