spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver # DB 커넥션과 관련된 데이터 소스 설정 완료
    # 이렇게만 써도 hikari를 써서 커넥션 풀 같은 것도 스부가 설정을 해준다

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true # 운영 환경에서는 logger 통해서 찍어야 함
        format_sql: true
logging:
  level:
    org.hibernate:
      SQL: debug
      orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6
